version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - ${SRC_PATH}:/var/www/html
    ports:
      - "8080:8080"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data: